### ISSUE TITLE
Hex: support dynamic size

### ISSUE THREAD

**Issue by barakugav** [poja/Cattus#110]
5,7,9,11

**Comment by poja** [comment]
My current training branch is size 4 hex.
Seems from Wikipedia that even sizes are legit.

Also, I would give this medium-low priority. It's not so important until we
solve one nontrivial hex board (eg 4x4)

**Comment by barakugav** [comment]
I prefer not to use temporary workarounds/fixes like changing all BOARD_SIZE to 4, and MOVE_NUM to 16. I think its better to do it as it should in the first plance, especially as this feature is really easy to implement

**Comment by barakugav** [comment]
3d0848fbd712c6311bb0f85ffeb880a4c7d37677
