### ISSUE TITLE
Tests: determinism test of the algorithm

### ISSUE THREAD

**Issue by poja** [poja/Cattus#93]
Make sure the algorithm is deterministic when temp=noise=0

**Comment by barakugav** [comment]
We can add such test now, but i think we will have to modify it in the future.
Currently we use multiple threads, each running a different search on a different game. In the future, we might want to use multiple threads in the same player, on the same tree search. This may result in a different searches even without random noise

**Comment by barakugav** [comment]
k cool, good idea

**Comment by barakugav** [comment]
So i guss such test will fail, due to the FP errors @poja

**Comment by poja** [comment]
Annoying, but seems true.
Maybe this is the "noise" they were talking about in the paper? 😅 
#87

**Comment by barakugav** [comment]
Maybe, they also have noise from multithreadind search
